### ISSUE TITLE
Library is unable to utilize secrets for config().

### ISSUE THREAD

**Issue by shgnplaatjies** [Bringittocode/cnad#1]
I tried using the following:
![image](https://github.com/syntanext/cnad/assets/63879125/6ae0a855-68da-4480-83e6-415f4c66f751)

But it consistently fails to build: 
![image](https://github.com/syntanext/cnad/assets/63879125/2b0d217e-525a-4956-b1db-6f91d7b96015)

From this line, which implies that the environment variable was not passed to the config method: 
 
![image](https://github.com/syntanext/cnad/assets/63879125/ec807fdf-e730-440e-99ab-3490a1ac9653)

**Comment by shgnplaatjies** [comment]
Given that you've obscured your username and node environment path, this is sensitive information you would not expect us to have in our repositories.


Could you let me know what you'd suggest to make this work?

**Comment by hazeezet** [comment]
> But it consistently fails to build

@shgnplaatjies While building on CI/CD the variable will be empty because env file is not included in your repository

**Comment by shgnplaatjies** [comment]
> > But it consistently fails to build
> 
> @shgnplaatjies While building on CI/CD the variable will be empty because env file is not included in your repository

What approach would you recommend? Will this only work with exposing the production file path?

**Comment by hazeezet** [comment]
@shgnplaatjies Check this https://docs.github.com/en/actions/learn-github-actions/variables

You need environment variables in your workflow

**Comment by shgnplaatjies** [comment]
You mean in the .github/workflow/deploy.yml?

Do I replace `run: npm ci` with `run: ${{secrets.NODE_DIR}} ci`

**Comment by hazeezet** [comment]
![Screenshot_2024-05-31-16-35-42-897_com brave browser-edit](https://github.com/syntanext/cnad/assets/52476329/e042ea59-9e4f-4822-bc84-b082700ed4a9)

You will need env in your workflow 

You see the "hello" that was mark you will replace it with your secret `${{secrets.NODE_DIR}}`

Replace greeting with `NODE_DIR`

**Comment by shgnplaatjies** [comment]
That worked!

Here's a further explanation on [StackOverflow](https://stackoverflow.com/questions/73373222/node-and-github-secrets-how-to-test-locally) (for anyone else who might see this)

Thanks again
